# - Try to find libWebsockets
# Once done this will define
#  LIBWEBSOCKETS_FOUND - System has libWebsockets
#  LIBWEBSOCKETS_INCLUDE_DIR - The libWebsockets include directories
#  LIBWEBSOCKETS_LIBRARIES - The libraries needed to use libWebsockets

FIND_PATH ( LIBWEBSOCKETS_INCLUDE_DIR libwebsockets.h
    ${LIBWEBSOCKETS_INCLUDE_DIR}
    /usr/local/include
    /usr/include
)

FIND_LIBRARY ( LIBWEBSOCKETS_LIBRARIES websockets
    ${LIBWEBSOCKETS_LIBRARY_DIR}
    /usr/local/lib
    /usr/lib
)

GET_FILENAME_COMPONENT( LIBWEBSOCKETS_LIBRARY_DIR ${LIBWEBSOCKETS_LIBRARIES} PATH )

SET ( LIBWEBSOCKETS_FOUND "NO" )
IF ( LIBWEBSOCKETS_INCLUDE_DIR )
    IF ( LIBWEBSOCKETS_LIBRARIES )
        SET ( LIBWEBSOCKETS_FOUND "YES" )
    ENDIF ( LIBWEBSOCKETS_LIBRARIES )
ENDIF ( LIBWEBSOCKETS_INCLUDE_DIR )

MARK_AS_ADVANCED(
    LIBWEBSOCKETS_LIBRARY_DIR
    LIBWEBSOCKETS_INCLUDE_DIR
    LIBWEBSOCKETS_LIBRARIES
)